-- 봄내마실 스키마 (R2-01 #4 — ③사용자 5종 + api_cache)
-- 이 파일은 scripts/export_schema.py 가 app/models/ 에서 생성한다. 손으로 고치지 말 것.
-- 적용: Supabase SQL Editor에 전체 붙여넣기 (또는 scripts/verify_r2_01.py 가 create_all로 동일 스키마 생성)

create extension if not exists postgis;

CREATE TABLE api_cache (
	cache_key VARCHAR NOT NULL, 
	payload JSONB NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (cache_key)
);

CREATE TABLE sessions (
	id VARCHAR NOT NULL, 
	nickname VARCHAR(12), 
	age_confirmed BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE quests (
	id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	recommendation_id VARCHAR NOT NULL, 
	rank INTEGER NOT NULL, 
	card JSONB NOT NULL, 
	activity_id VARCHAR NOT NULL, 
	merchant_id VARCHAR, 
	board_stop_id VARCHAR NOT NULL, 
	alight_stop_id VARCHAR NOT NULL, 
	status VARCHAR NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_quests_status CHECK (status in ('recommended','started','stamped','recorded','abandoned')), 
	FOREIGN KEY(session_id) REFERENCES sessions (id) ON DELETE CASCADE
);

CREATE INDEX ix_quests_recommendation_id ON quests (recommendation_id);

CREATE INDEX ix_quests_session_status ON quests (session_id, status);

CREATE UNIQUE INDEX uq_quests_one_in_progress ON quests (session_id) WHERE status IN ('started', 'stamped');

CREATE TABLE point_ledger (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	session_id VARCHAR NOT NULL, 
	quest_id VARCHAR NOT NULL, 
	delta INTEGER NOT NULL, 
	reason VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(session_id) REFERENCES sessions (id) ON DELETE CASCADE, 
	FOREIGN KEY(quest_id) REFERENCES quests (id) ON DELETE CASCADE
);

CREATE INDEX ix_point_ledger_quest_id ON point_ledger (quest_id);

CREATE INDEX ix_point_ledger_session_id ON point_ledger (session_id);

CREATE TABLE records (
	id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	quest_id VARCHAR NOT NULL, 
	purpose VARCHAR NOT NULL, 
	answers JSONB NOT NULL, 
	title VARCHAR NOT NULL, 
	body TEXT NOT NULL, 
	tags JSONB NOT NULL, 
	verified BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_records_purpose CHECK (purpose in ('portfolio','hobby','learning')), 
	FOREIGN KEY(session_id) REFERENCES sessions (id) ON DELETE CASCADE, 
	UNIQUE (quest_id), 
	FOREIGN KEY(quest_id) REFERENCES quests (id) ON DELETE CASCADE
);

CREATE INDEX ix_records_session_id ON records (session_id);

CREATE TABLE stamps (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY, 
	session_id VARCHAR NOT NULL, 
	quest_id VARCHAR NOT NULL, 
	merchant_id VARCHAR NOT NULL, 
	stamp_type VARCHAR NOT NULL, 
	amount_krw INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_stamps_type CHECK (stamp_type in ('visit','spend')), 
	CONSTRAINT ck_stamps_amount_iff_spend CHECK ((stamp_type = 'spend') = (amount_krw is not null)), 
	FOREIGN KEY(session_id) REFERENCES sessions (id) ON DELETE CASCADE, 
	UNIQUE (quest_id), 
	FOREIGN KEY(quest_id) REFERENCES quests (id) ON DELETE CASCADE
);

CREATE INDEX ix_stamps_session_id ON stamps (session_id);
