import React from "react";
import { api } from "../api/client";
import { ACCESSIBILITY_COLORS, DashboardMap, INFLOW_COLORS } from "../components/dashboard/DashboardMap";

export function DashboardPage() {
  const [layer, setLayer] = React.useState("accessibility"); const [dashboard, setDashboard] = React.useState(null); const [error, setError] = React.useState("");
  React.useEffect(() => { let mounted = true; Promise.all([api.getDashboardAccessibility(), api.getDashboardInflow(), api.getDashboardKpi()]).then(([accessibility, inflow, kpi]) => { if (mounted) setDashboard({ accessibility, inflow, kpi }); }).catch(() => { if (mounted) setError("잠시 문제가 있었어요. 다시 시도해 주세요"); }); return () => { mounted = false; }; }, []);
  if (error) return <main className="dashboard-page"><section className="dashboard-error"><h1>정책 대시보드</h1><p>{error}</p><button type="button" onClick={() => window.location.reload()}>다시 시도</button></section></main>;
  if (!dashboard) return <main className="dashboard-page"><section className="dashboard-loading"><p>정책 데이터를 불러오는 중이에요.</p></section></main>;
  const mapData = layer === "accessibility" ? dashboard.accessibility : dashboard.inflow;
  const kpiCards = [["방문 전환율", dashboard.kpi.conversion_pct === null ? "—" : `${dashboard.kpi.conversion_pct}%`, "가게 미션 시작 후 인증 비율"], ["저유입 추천 비중", dashboard.kpi.low_inflow_pct === null ? "—" : `${dashboard.kpi.low_inflow_pct}%`, "추천 카드 중 저유입 상권 비중"], ["탐색 시간(중앙값)", dashboard.kpi.median_search_min === null ? "—" : `${dashboard.kpi.median_search_min}분`, "세션 생성부터 첫 퀘스트 시작까지"], ["실행 가능성", dashboard.kpi.feasibility_pct === null ? "—" : `${dashboard.kpi.feasibility_pct}%`, "무환승 경로를 보유한 추천 비율"]];
  return <main className="dashboard-page"><header className="dashboard-header"><a href="/">봄내마실</a><span>춘천시 정책 대시보드</span><small>시범 운영</small></header><section className="dashboard-intro"><p>정책 인사이트</p><h1>시민의 이동 경험이<br />지역 상권으로 이어지는 흐름</h1><span>추천 엔진의 접근성·상권 데이터를 한눈에 확인하세요.</span></section><section className="dashboard-grid"><article className="dashboard-map-card"><div className="dashboard-card-heading"><div><p>지역 현황 지도</p><h2>{layer === "accessibility" ? "동별 접근성 히트맵" : "상권 방문 현황"}</h2></div><span>{mapData.features.length}개 영역</span></div><div className="dashboard-tabs" role="tablist" aria-label="지도 종류"><button type="button" role="tab" aria-selected={layer === "accessibility"} className={layer === "accessibility" ? "selected" : ""} onClick={() => setLayer("accessibility")}>접근성 지도</button><button type="button" role="tab" aria-selected={layer === "inflow"} className={layer === "inflow" ? "selected" : ""} onClick={() => setLayer("inflow")}>상권 현황</button></div><div className="dashboard-map-wrap"><DashboardMap layer={layer} data={mapData} /></div>{layer === "accessibility" ? <div className="dashboard-legend"><span>높음</span>{[1, 2, 3, 4, 5].map((value) => <i key={value} style={{ background: ACCESSIBILITY_COLORS[value] }} />)}<span>낮음</span></div> : <div className="dashboard-legend inflow-legend">{Object.entries(INFLOW_COLORS).map(([label, color]) => <span key={label}><i style={{ background: color }} />{label}</span>)}</div>}</article><section className="dashboard-kpi-panel"><div className="dashboard-card-heading"><div><p>운영 성과</p><h2>핵심 지표</h2></div></div><div className="dashboard-kpi-grid">{kpiCards.map(([label, value, detail]) => <article className="dashboard-kpi" key={label}><p>{label}</p><strong>{value}</strong><span>{detail}</span></article>)}</div><p className="dashboard-footnote">{dashboard.kpi.seed_included ? "시범 운영 시뮬레이션 데이터 포함" : "운영 데이터 기준"}</p></section></section></main>;
}
