import React from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { api } from "../api/client";
import { CollectionCard, CollectionModal, PieceRevealModal, findDongByPoint, isCollectible, useCollection } from "../collection-map";
import { BottomNav } from "../components/layout/BottomNav";
import { serviceDateOf } from "../utils/date";
import { useBackTo } from "../hooks/useNavigation";
import { useSessionRecovery } from "../hooks/useSessionRecovery";

const RECORD_QUESTIONS = [
  { question: "오늘 가장 기억에 남는 순간은 무엇인가요?", chips: ["새로운 풍경", "따뜻한 대화", "몰입했던 순간"] },
  { question: "새롭게 알게 된 점이 있나요?", chips: ["춘천의 새로운 장소", "활동의 즐거움", "가게의 이야기"] },
  { question: "다음에는 어떻게 해보고 싶나요?", chips: ["다른 코스도 가보기", "친구와 함께", "다시 천천히"] },
];

function useServiceDate() { const [health, setHealth] = React.useState(null); React.useEffect(() => { api.health().then(setHealth).catch(() => setHealth(null)); }, []); return serviceDateOf(health); }

export function RecordPage() {
  const { questId } = useParams(); const navigate = useNavigate(); const location = useLocation(); const recoverSession = useSessionRecovery(); const goBackArchive = useBackTo("/"); const goBackWrite = useBackTo(questId ? `/quests/${questId}` : "/"); const mode = questId ? "write" : "archive";
  const [collectionOpen, setCollectionOpen] = React.useState(false); const serviceDate = useServiceDate(); const [purpose, setPurpose] = React.useState("hobby"); const [answers, setAnswers] = React.useState(["", "", ""]); const [pickedChips, setPickedChips] = React.useState([null, null, null]); const [draft, setDraft] = React.useState(null); const [regenerations, setRegenerations] = React.useState(0); const [generating, setGenerating] = React.useState(false); const [slowNotice, setSlowNotice] = React.useState(false); const [saving, setSaving] = React.useState(false); const saveResult = location.state?.saved ?? null; const [quest, setQuest] = React.useState(null); const [records, setRecords] = React.useState([]); const [balance, setBalance] = React.useState(0); const [titles, setTitles] = React.useState([]); const [selectedRecord, setSelectedRecord] = React.useState(null); const [deleteOpen, setDeleteOpen] = React.useState(false); const [error, setError] = React.useState(""); const [reveal, setReveal] = React.useState(null); const revealNextRef = React.useRef(null); const { zoneMap: collectionZoneMap, features: collectionFeatures } = useCollection();
  const resolvedAnswers = answers.map((answer, index) => answer.trim() || (pickedChips[index] ?? "")); const hasAnswer = resolvedAnswers.some(Boolean);
  const loadArchive = React.useCallback(async () => { try { const data = await api.getRecords(); setRecords(data.records ?? []); setBalance(data.balance ?? 0); setTitles(data.titles ?? []); } catch (requestError) { if (recoverSession(requestError)) return; setError(requestError?.error?.message ?? "잠시 문제가 있었어요. 다시 시도해 주세요"); } }, [recoverSession]);
  React.useEffect(() => { loadArchive().then(() => { const savedRecord = location.state?.savedRecord; if (savedRecord) setRecords((current) => [savedRecord, ...current.filter((record) => record.record_id !== savedRecord.record_id)]); }); }, [loadArchive, mode, location.state]);
  React.useEffect(() => { if (!questId) return; api.getQuest(questId).then(setQuest).catch((requestError) => { if (!recoverSession(requestError)) setError("퀘스트 정보를 불러오지 못했어요."); }); }, [questId]);
  function chooseChip(questionIndex, chip) { setPickedChips((current) => current.map((value, index) => index === questionIndex ? (value === chip ? null : chip) : value)); }
  async function generateDraft() { if (!questId || generating || (draft && regenerations >= 2)) return; setGenerating(true); setError(""); setSlowNotice(false); const template = { title: "오늘의 춘천 기록", body: "오늘은 춘천에서 나만의 시간을 보냈습니다. 활동을 따라 천천히 걸으며 평소에는 지나치던 풍경과 이야기를 새롭게 만났습니다. 작은 선택 하나가 하루를 조금 더 풍성하게 만들었고, 다음에는 오늘의 경험을 바탕으로 또 다른 코스를 찾아보고 싶습니다.", tags: ["춘천", "오늘", "기록"] }; try { const timeout = new Promise((resolve) => window.setTimeout(() => resolve({ draft: template, from_template: true }), 8000)); const response = await Promise.race([api.generateRecord({ quest_id: questId, action: "generate", purpose, answers: resolvedAnswers, attempt: regenerations }), timeout]); setDraft(response.draft); setSlowNotice(Boolean(response.from_template)); if (draft) setRegenerations((count) => count + 1); } catch (requestError) { if (recoverSession(requestError)) return; setDraft(template); setSlowNotice(true); } finally { setGenerating(false); } }
  async function saveRecord() { if (!questId || !draft || saving) return; setSaving(true); setError(""); try { const response = await api.saveRecord({ quest_id: questId, action: "save", purpose, answers: resolvedAnswers, final: draft }); localStorage.removeItem("active_quest_id"); const completedRecord = { record_id: response.record_id, title: draft.title, tags: draft.tags, created_at: `${serviceDate}T14:00:00`, verified: response.verified, body: draft.body }; const goArchive = () => navigate("/records", { replace: true, state: { saved: response, savedRecord: completedRecord } }); const activity = quest?.coords?.activity; const feature = activity ? findDongByPoint(collectionFeatures, activity.lat, activity.lng) : null; const zoneCodeOfQuest = feature?.properties?.zone_code; if (feature && isCollectible(feature, collectionZoneMap) && !collectionZoneMap.collected.includes(zoneCodeOfQuest)) { revealNextRef.current = goArchive; setReveal(feature); } else goArchive(); } catch (requestError) { if (recoverSession(requestError)) return; setError(requestError?.error?.message ?? "잠시 문제가 있었어요. 다시 시도해 주세요"); } finally { setSaving(false); } }
  async function deleteAll() { const sessionId = localStorage.getItem("session_id"); if (!sessionId) { navigate("/"); return; } try { await api.deleteSession(sessionId); localStorage.removeItem("session_id"); localStorage.removeItem("active_quest_id"); window.dispatchEvent(new Event("bomnae-session-changed")); navigate("/"); } catch { setError("잠시 문제가 있었어요. 다시 시도해 주세요"); setDeleteOpen(false); } }
  if (selectedRecord) return <main className="app-shell record-page"><section className="record-content readonly-record"><header className="record-head"><button onClick={() => setSelectedRecord(null)}>‹</button><h1>나의 기록</h1><strong>{balance.toLocaleString()}P</strong></header><p className="record-date">{selectedRecord.created_at.slice(0, 10).replaceAll("-", ".")}</p><h2>{selectedRecord.title}</h2><div className="record-tags">{selectedRecord.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div>{!selectedRecord.verified && <span className="unverified-badge">인증 없음</span>}<article>{selectedRecord.body ?? "이 기록의 본문은 생성 당시 읽기 전용으로 보관됩니다."}</article></section><BottomNav active="archive" /></main>;
  if (mode === "archive") return <main className="app-shell record-page"><section className="record-content archive-content"><header className="record-head"><button onClick={goBackArchive}>‹</button><h1>보관함</h1><strong>{balance.toLocaleString()}P</strong></header><p className="archive-lead">오늘의 경험을 차곡차곡 모아 보세요.</p>{titles.map((title) => <span className="archive-title" key={title}>✦ {title}</span>)}<CollectionCard onOpen={() => setCollectionOpen(true)} />{collectionOpen && <CollectionModal onClose={() => setCollectionOpen(false)} />}{saveResult && <p className="record-earned">{saveResult.points_added > 0 ? `기록 +${saveResult.points_added}P` : "기록을 저장했어요"}{saveResult.completion_bonus > 0 ? ` · 완주 보너스 +${saveResult.completion_bonus}P` : ""}</p>}<section className="archive-list">{records.length ? records.map((record) => <button className="archive-card" key={record.record_id} onClick={() => setSelectedRecord(record)}><small>{record.created_at.slice(0, 10).replaceAll("-", ".")}</small><b>{record.title}</b><span>{record.tags.map((tag) => `#${tag}`).join("  ")}</span>{!record.verified && <em>인증 없음</em>}</button>) : <p className="archive-empty">아직 저장한 기록이 없어요.<br />오늘의 경험을 첫 기록으로 남겨 보세요.</p>}</section>{error && <p className="form-error">{error}</p>}<button className="delete-records" type="button" onClick={() => setDeleteOpen(true)}>내 기록 전체 삭제</button></section><BottomNav active="archive" />{deleteOpen && <div className="modal-backdrop delete-modal"><section role="dialog" aria-modal="true"><h2>기록을 모두 삭제할까요?</h2><p>모든 기록·스탬프·포인트가 삭제돼요.<br />개인 식별이 불가능한 통계는 유지됩니다.</p><div><button onClick={() => setDeleteOpen(false)}>취소</button><button onClick={deleteAll}>전체 삭제</button></div></section></div>}</main>;
  return <main className="app-shell record-page"><section className="record-content"><header className="record-head"><button onClick={goBackWrite}>‹</button><h1>오늘을 기록해 볼까요?</h1><strong>{balance.toLocaleString()}P</strong></header><p className="record-subtitle">짧게 답해 주시면 오늘의 경험을 기록으로 정리해 드려요.</p><section className="purpose-section"><h2>이 기록을 어디에 쓸까요?</h2><div>{[["portfolio", "포트폴리오"], ["hobby", "취미 아카이브"], ["learning", "배움일지"]].map(([value, label]) => <button className={purpose === value ? "selected" : ""} key={value} onClick={() => setPurpose(value)}>{label}</button>)}</div></section><p className="privacy-hint">실명·연락처는 적지 마세요.</p>{RECORD_QUESTIONS.map((item, index) => <section className="record-question" key={item.question}><h2>{index + 1}. {item.question}</h2><div className="answer-chips">{item.chips.map((chip) => <button className={pickedChips[index] === chip ? "selected" : ""} key={chip} onClick={() => chooseChip(index, chip)}>{chip}</button>)}</div><textarea value={answers[index]} maxLength={200} placeholder="직접 적어도 좋아요 (최대 200자)" onChange={(event) => setAnswers((current) => current.map((value, answerIndex) => answerIndex === index ? event.target.value : value))} /></section>)}{!hasAnswer && <p className="answer-warning">한 가지만 골라주시면 포인트가 적립돼요 (+60점)</p>}<button className="draft-button" disabled={generating || Boolean(draft && regenerations >= 2)} onClick={generateDraft}>{generating ? "AI가 기록을 정리하고 있어요…" : draft ? `다시 생성 (${2 - regenerations}회 남음)` : "AI 초안 만들기"}</button>{slowNotice && <p className="slow-notice">연결이 느려 기본 초안을 먼저 드려요.</p>}{draft && <section className="draft-editor"><h2>AI 초안</h2><input value={draft.title} maxLength={100} onChange={(event) => setDraft((current) => ({ ...current, title: event.target.value }))} /><textarea value={draft.body} maxLength={500} onChange={(event) => setDraft((current) => ({ ...current, body: event.target.value }))} /><div className="record-tags">{draft.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div><button className="primary-button" onClick={saveRecord} disabled={saving}>{saving ? "저장하는 중…" : "기록 저장하기"}</button></section>}{error && <p className="form-error">{error}</p>}</section><BottomNav active="quest" />{reveal && <PieceRevealModal feature={reveal} features={collectionFeatures} zoneMap={collectionZoneMap} onDone={() => { setReveal(null); const next = revealNextRef.current; revealNextRef.current = null; if (next) next(); }} />}</main>;
}
