import React from "react";
import { Html5Qrcode } from "html5-qrcode";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { api } from "../api/client";
import { QrMark } from "../components/common/QrMark";
import { BottomNav } from "../components/layout/BottomNav";
import { VerificationResultModal } from "../components/verify/VerificationResultModal";
import { useBackTo } from "../hooks/useNavigation";
import { useSessionRecovery } from "../hooks/useSessionRecovery";

export function VerifyPage() {
  const { questId } = useParams(); const navigate = useNavigate(); const location = useLocation(); const goBack = useBackTo(`/quests/${questId}`); const recoverSession = useSessionRecovery();
  const [quest, setQuest] = React.useState(null); const [method, setMethod] = React.useState(location.state?.code ? "code" : "qr"); const [code, setCode] = React.useState(location.state?.code ?? ""); const [amount, setAmount] = React.useState(""); const [receiptName, setReceiptName] = React.useState(""); const [result, setResult] = React.useState(null); const [error, setError] = React.useState(""); const [scanning, setScanning] = React.useState(false);
  function closeResult(next) { setResult(null); if (next) next(); }
  React.useEffect(() => { let mounted = true; api.getQuest(questId).then((data) => { if (!mounted) return; if (!data.mission) { navigate(`/records/${questId}`, { replace: true }); return; } setQuest(data); }).catch((requestError) => { if (mounted) recoverSession(requestError); }); return () => { mounted = false; }; }, [questId]);
  React.useEffect(() => { if (!scanning) return undefined; const scanner = new Html5Qrcode("verify-qr-reader"); scanner.start({ facingMode: "environment" }, { fps: 10, qrbox: { width: 210, height: 210 } }, (text) => { let scannedCode = ""; let merchantId = ""; try { const payload = new URL(text); scannedCode = payload.searchParams.get("c") ?? ""; merchantId = payload.searchParams.get("m") ?? ""; } catch { scannedCode = text.slice(-4); } setCode(scannedCode); setScanning(false); verifyCode(scannedCode, "qr", merchantId); }, () => {}).catch(() => { setScanning(false); setError("카메라를 열 수 없어요. 4자리 코드로 인증해 주세요."); }); return () => { scanner.stop().catch(() => {}); }; }, [scanning]);
  React.useEffect(() => { if (!result) return undefined; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previousOverflow; }; }, [result]);
  async function verifyCode(value, verificationMethod = "code", merchantId = null) { if (value.length !== 4) { setError("QR 코드를 다시 비춰 주세요."); return; } const scenario = quest?.status === "stamped" ? "already" : value === "0000" ? "already" : value !== "2097" ? "fail" : "success"; try { const body = verificationMethod === "qr" ? { method: "qr", merchant_id: merchantId, code: value } : { method: "code", code: value }; const response = await api.verifyQuest(questId, body, scenario); setResult(response); if (!response.already) setQuest((current) => (current ? { ...current, status: "stamped" } : current)); } catch (requestError) { if (recoverSession(requestError)) return; setError(requestError?.error?.message ?? "잠시 문제가 있었어요. 다시 시도해 주세요"); } }
  async function verify() { setError(""); if (method === "qr") { setError("QR 스캔을 먼저 완료해 주세요."); return; } if (method === "receipt" && (!receiptName || !amount || Number(amount) < 1000 || Number(amount) > 200000)) { setError("금액을 확인해 주세요 (1,000~200,000원)"); return; } if (method === "code" && code.length !== 4) { setError("4자리 코드를 입력해 주세요."); return; } if (method === "code") { await verifyCode(code); return; } try { const response = await api.verifyQuest(questId, { method: "receipt", amount_krw: Number(amount) }, quest?.status === "stamped" ? "already" : "success"); setResult(response); if (!response.already) setQuest((current) => (current ? { ...current, status: "stamped" } : current)); } catch (requestError) { if (recoverSession(requestError)) return; setError(requestError?.error?.message ?? "잠시 문제가 있었어요. 다시 시도해 주세요"); } }
  const codeTap = (key) => setCode((value) => key === "del" ? value.slice(0, -1) : value.length < 4 ? value + key : value); const formattedAmount = amount ? Number(amount).toLocaleString("ko-KR") : "";
  return <main className={`app-shell verify-page${result ? " is-complete" : ""}`}><section className="verify-content"><header className="verify-head"><button onClick={goBack}>‹</button><h1>가게 미션 인증</h1><b>40P</b></header><div className="merchant-card"><small>미션 장소</small><strong>{quest?.mission?.merchant_name ?? "미션 정보를 불러오는 중…"}</strong>{quest?.mission?.copy && <p>{quest.mission.copy}</p>}</div>{quest?.status === "stamped" && !result && <p className="verify-done">이미 적립된 퀘스트예요 — 기록만 남기면 완주!</p>}<div className="verify-tabs">{[["qr", "QR 스캔"], ["code", "4자리 코드"], ["receipt", "영수증"]].map(([key, label]) => <button key={key} className={method === key ? "selected" : ""} onClick={() => { setMethod(key); setError(""); }}>{label}</button>)}</div>{method === "qr" && <div className="verify-panel qr-panel"><div className={`qr-frame${scanning ? " scanning" : ""}`}>{scanning ? <div id="verify-qr-reader" /> : <><QrMark /><p>가게의 QR 스탠드를 비춰주세요</p></>}</div>{!scanning && <button className="scan-button" onClick={() => setScanning(true)}>QR 스캔 시작</button>}<p>카메라가 안 되면 4자리 코드 탭을 이용해 주세요</p></div>}{method === "code" && <div className="verify-panel code-panel"><p>QR 스탠드 아래 적힌 4자리 숫자를 입력해 주세요</p><div className="code-boxes">{[0, 1, 2, 3].map((index) => <i key={index}>{code[index] || ""}</i>)}</div><div className="keypad">{["1", "2", "3", "4", "5", "6", "7", "8", "9", "", "0", "del"].map((key) => <button key={key} disabled={!key} onClick={() => codeTap(key)}>{key === "del" ? "⌫" : key}</button>)}</div></div>}{method === "receipt" && <div className="verify-panel receipt-panel"><p>협약이 안 된 가게도 괜찮아요. 영수증 사진과 금액만 있으면 미션 완료!</p><label className="receipt-upload"><b>＋</b>영수증 사진 찍기 / 올리기<input type="file" accept="image/*" onChange={(event) => setReceiptName(event.target.files?.[0]?.name ?? "")} /></label><small>사진은 저장되지 않아요 — 확인 후 바로 폐기돼요</small><input className="receipt-amount" inputMode="numeric" value={formattedAmount} onChange={(event) => setAmount(event.target.value.replace(/\D/g, ""))} placeholder="결제 금액 (1,000~200,000원)" /></div>}{error && <p className="form-error">{error}</p>}<button className="primary-button verify-submit" onClick={verify}>{method === "receipt" ? "소비 인증하기" : "인증하고 +40P 받기"}</button><button className="text-action record-without" onClick={() => navigate(`/records/${questId}`)}>인증 없이 기록만 남길래요</button></section><BottomNav active="quest" />{result && <VerificationResultModal result={result} merchantName={quest?.mission?.merchant_name} onRecord={() => closeResult(() => navigate(`/records/${questId}`))} onLater={() => closeResult()} />}</main>;
}
